"use client";

import { useEffect, useState } from "react";
import { AppShell } from "../../components/app-shell";
import { generateDecision, getLatestDecision, getWorkspace, updateDecision, type DecisionBrief, type WorkspaceContext } from "../../lib/veriq-api";
import "./decision-brief.css";

function displayDate(value: string) {
  return new Intl.DateTimeFormat("en-ZW", { day: "numeric", month: "short", year: "numeric", timeZone: "Africa/Harare" }).format(new Date(`${value}T12:00:00`));
}

export default function DecisionBriefPage() {
  const [decision, setDecision] = useState<DecisionBrief | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [working, setWorking] = useState(false);
  const [workspace, setWorkspace] = useState<WorkspaceContext | null>(null);
  useEffect(() => { getWorkspace().then(setWorkspace).catch(() => undefined); getLatestDecision().then(setDecision).catch((requestError) => setError(requestError instanceof Error ? requestError.message : "The current Decision Brief could not be loaded.")); }, []);
  const generate = async () => { setWorking(true); setError(null); try { setDecision(await generateDecision()); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Beacon could not generate the brief."); } finally { setWorking(false); } };
  const assign = async () => { if (!decision) return; setWorking(true); try { setDecision(await updateDecision(decision.id, { owner: workspace?.user_name ?? "School leadership", status: "assigned" })); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "The owner could not be assigned."); } finally { setWorking(false); } };

  if (!decision) return <AppShell activeNavigation="Decision Brief"><main className="decision-brief-page"><header className="decision-brief-intro"><p className="decision-eyebrow">DECISION BRIEF</p><div className="decision-heading-row"><div><h1>Turn the current evidence into accountable action.</h1><p>{error ?? "Beacon is checking for a Decision Brief connected to the latest analysis."}</p></div></div></header><section className="decision-primary-card"><div className="decision-primary-copy"><p className="decision-eyebrow">BEACON</p><h2>No brief exists for the current analysis yet.</h2><p>Generate one from the same evidence used by School Pulse and Early Intervention.</p><button type="button" className="decision-assign" onClick={() => void generate()} disabled={working}>{working ? "Beacon is generating…" : "Generate Decision Brief"}</button></div></section></main></AppShell>;

  const assigned = decision.status === "assigned" || decision.status === "in_progress" || decision.status === "completed";
  return <AppShell activeNavigation="Decision Brief"><main className="decision-brief-page">
    <header className="decision-brief-intro"><p className="decision-eyebrow">DECISION BRIEF · {(decision.scope_label ?? decision.class_name).toUpperCase()}</p><div className="decision-heading-row"><div><h1>{decision.title}</h1><p>{decision.situation}</p></div><div className="decision-confidence"><span>CONFIDENCE</span><strong>{decision.confidence}%</strong><small>{decision.scope_type ?? "class"} scope · Analysis {decision.analysis_id.slice(-8)}</small></div></div></header>
    {error ? <p className="integration-inline-error">{error}</p> : null}
    <section className="decision-primary-card" aria-labelledby="recommended-action-title"><div className="decision-primary-copy"><p className="decision-eyebrow">BEACON RECOMMENDATION</p><h2 id="recommended-action-title">One evidence-grounded response for leadership review.</h2><p>{decision.recommendation}</p></div><div className="decision-priority"><span>PRIORITY</span><strong>{decision.priority}</strong><small>Derived from the current signal strength</small></div></section>
    <section className="decision-accountability" aria-label="Decision accountability"><div><span>OWNER</span><strong>{decision.owner}</strong><small>Accountable role</small></div><div><span>DUE DATE</span><strong>{displayDate(decision.due_date)}</strong><small>Review {displayDate(decision.review_date)}</small></div><div><span>STATUS</span><strong className={assigned ? "status-assigned" : "status-open"}>{decision.status.replace("_", " ")}</strong><small>Persisted with this Decision Object</small></div><div><span>SUCCESS METRIC</span><strong>{decision.success_metric}</strong><small>Response target, not a prediction</small></div></section>
    <section className="decision-outcomes page-reveal" aria-labelledby="expected-outcome-title"><div className="decision-outcomes-heading"><div><p className="decision-eyebrow">EXPECTED OUTCOME</p><h2 id="expected-outcome-title">What meaningful progress should look like.</h2></div><small>Response targets, not predictions</small></div><div className="decision-outcome-list">{decision.expected_outcomes.map((outcome) => <div key={outcome.label}><span>{outcome.label}</span><strong>{outcome.current} <b>→</b> {outcome.target}</strong><small>{outcome.note}</small></div>)}</div></section>
    <section className="decision-detail-grid"><article className="decision-evidence-panel"><p className="decision-eyebrow">WHY THIS BRIEF EXISTS</p><h2>{decision.why_it_matters}</h2><p className="decision-evidence-summary">Every item below is attached to trace {decision.trace_id.slice(-8)}.</p><div className="decision-evidence-list">{decision.evidence_summary.map((detail, index) => <div key={detail} className="decision-evidence-row"><span className="decision-evidence-dot critical" /><p>Evidence {index + 1}</p><strong>{detail}</strong></div>)}</div><div className="decision-unknown"><strong>Still unknown</strong><span>{decision.missing_evidence[0] ?? "No missing evidence was reported in the required upload."}</span></div></article><aside className="decision-action-panel"><p className="decision-eyebrow">HUMAN REVIEW</p><h2>Beacon recommends. School leadership decides.</h2><p>{decision.actions.join(" ")}</p><button type="button" className="decision-assign" onClick={() => void assign()} disabled={assigned || working}>{assigned ? "Owner assigned" : working ? "Saving…" : `Assign ${workspace?.user_name ?? "school leader"} →`}</button>{assigned ? <p className="decision-confirmation" role="status">This assignment is saved and will remain after refresh or backend restart.</p> : null}</aside></section>
    <section className="decision-monitoring"><span>✦</span><div><p className="decision-eyebrow">MONITORING</p><strong>Future uploads create a new analysis without rewriting this Decision Object.</strong><small>Leadership can compare the next evidence snapshot with these response targets.</small></div></section>
    <section className="decision-lifecycle" aria-label="Decision lifecycle"><p className="decision-eyebrow">DECISION LIFECYCLE</p><ol><li className="complete"><span>1</span>Generated</li><li className={assigned ? "complete" : "active"}><span>2</span>Human review</li><li className={assigned ? "active" : ""}><span>3</span>Assigned</li><li><span>4</span>Measured</li></ol></section>
  </main></AppShell>;
}
